# FROM node:4.8.4-alpine
FROM node:4.8.4
MAINTAINER Den Norske Turistforening <tekno@dnt.no>

# Note: npm is v2.14.10
RUN npm install -g ember-cli@1.13.8
RUN npm install -g bower@1.5.2
RUN npm install -g phantomjs@1.9.19

# install git
# RUN apk update && apk upgrade && \
#     apk add --no-cache bash git openssh zip python python-dev make autoconf automake gcc g++ linux-headers

# install watchman
# RUN \
# 	git clone https://github.com/facebook/watchman.git &&\
# 	cd watchman &&\
# 	git checkout v3.5.0 &&\
# 	./autogen.sh &&\
# 	./configure &&\
# 	make &&\
# 	make install

# RUN git clone https://github.com/facebook/watchman.git && \
#     cd watchman && git checkout v4.7.0 && \
#     ./autogen.sh && ./configure && \
#     make && make install

EXPOSE 4200 49152 35729
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# run ember server on container start
# ENTRYPOINT ["/usr/local/bin/ember"]
# CMD ["server"]

# FROM node:argon-slim
#
# RUN groupadd -r app && useradd -r -d /usr/src/app -g app app \
#  && apt-get -y --no-install-recommends update \
#  && apt-get -y --no-install-recommends install git \
#  && mkdir -p /usr/src/app
#
# WORKDIR /usr/src/app
# CMD [ "/bin/true" ]
#
# COPY package.json /usr/src/app/
# RUN npm install
#
# COPY bower.json /usr/src/app/
# RUN npm run bower
#
# COPY . /usr/src/app
#
# RUN chown -R app:app /usr/src/app \
#  && runuser -l app -c 'npm run build' \
#  && apt-get -y autoclean \
#  && apt-get -y autoremove \
#  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
