version: '2'

services:
  www:
    network_mode: 'bridge'
    build: nginx
    volumes:
      - ./nginx/develop.client:/etc/nginx/conf.d/default.client
    links:
      - server
      - client
    depends_on:
      - server
      - client
    ports:
      - "8080"
    environment:
      - VIRTUAL_HOST=hytte.app.dnt.local
      - VIRTUAL_PORT=8080

  redis:
    network_mode: 'bridge'
    image: redis:3.0

  server:
    network_mode: 'bridge'
    # build: server
    image: node:7.8.0-alpine
    # user: app
    links:
      - redis
    ports:
      - "8080"
    volumes:
      - ./server:/usr/src/app
      # - ./server/controllers:/usr/src/app/controllers
      # - ./server/lib:/usr/src/app/lib
      # - ./server/db:/usr/src/app/db
      # - ./server/index.js:/usr/src/app/index.js
      # - ./server/package.json:/usr/src/app/package.json
      # - ./server/test:/usr/src/app/test
    working_dir: /usr/src/app
    env_file: .env
    environment:
      - APP_URL=http://hytte.app.dnt.local
      - APP_PORT=8080
      - NTB_API_ENV=dev
      - NODE_ENV=development
    command: npm start

  # npm:
  #   image: danlynn/ember-cli:1.13.15
  #   volumes:
  #     - ./client:/usr/src/app
  #   working_dir: /usr/src/app
  #   entrypoint: ['/usr/local/bin/npm']
  #
  # bower:
  #   image: danlynn/ember-cli:1.13.15
  #   volumes:
  #     - ./client:/usr/src/app
  #   working_dir: /usr/src/app
  #   entrypoint: ['/usr/local/bin/bower', '--allow-root']
  #
  client:
    network_mode: 'bridge'
    # build: client
    # image: danlynn/ember-cli:1.13.15
    build:
      context: client
      dockerfile: Dockerfile-dev
    volumes:
      # - ./client/app:/usr/src/app/app
      # - ./client/config:/usr/src/app/config
      # - ./client/ember-cli-build.js:/usr/src/app/ember-cli-build.js
      # - ./client/public:/usr/src/app/public
      # - ./client/testem.json:/usr/src/app/testem.json
      # - ./client/tests:/usr/src/app/tests
      # - ./client/vendor:/usr/src/app/vendor
      - ./client:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "4200"
      - "35729:35729"
      - "49152:49152"
    environment:
      - NODE_ENV=development
      - SENTRY_DSN=https://0a174e389f194b64bcedc49ecd8bfcb5@sentry.io/83453
    command: ember server --watcher
