www:
  build: nginx
  volumes:
    - nginx/develop.conf:/etc/nginx/conf.d/default.conf
  links:
    - server
    - client
  ports:
    - "8080"
  environment:
    - VIRTUAL_HOST=hytte.app.dnt.privat
    - VIRTUAL_PORT=8080

redis:
  image: redis

server:
  build: server
  user: app
  links:
    - redis
  ports:
    - "8080"
  volumes:
    - server/controllers:/usr/src/app/controllers
    - server/db:/usr/src/app/db
    - server/index.js:/usr/src/app/index.js
    - server/test:/usr/src/app/test
  working_dir: /usr/src/app
  env_file: .env
  environment:
    - APP_URL=http://hytte.app.dnt.privat
    - APP_PORT=8080
    - NTB_API_ENV=dev
    - NODE_ENV=development
  command: npm start

client:
  build: client
  volumes:
    - client/app:/usr/src/app/app
    - client/config:/usr/src/app/config
    - client/ember-cli-build.js:/usr/src/app/ember-cli-build.js
    - client/public:/usr/src/app/public
    - client/testem.json:/usr/src/app/testem.json
    - client/tests:/usr/src/app/tests
    - client/vendor:/usr/src/app/vendor
  ports:
    - "4200"
    - "35729:35729"
    - "49152:49152"
  environment:
    - NODE_ENV=development
  command: npm start
